// flow-typed signature: 911aea09cedec0bfbe8626a72ef652c9
// flow-typed version: <<STUB>>/app_v^0.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'app/lib/App' {
  declare module.exports: any;
}

declare module 'app/lib/Controller' {
  declare module.exports: any;
}

declare module 'app/lib/index' {
  declare module.exports: any;
}

declare module 'app/lib/Model' {
  declare module.exports: any;
}

// Filename aliases
declare module 'app/lib/App.js' {
  declare module.exports: $Exports<'app/lib/App'>;
}
declare module 'app/lib/Controller.js' {
  declare module.exports: $Exports<'app/lib/Controller'>;
}
declare module 'app/lib/index.js' {
  declare module.exports: $Exports<'app/lib/index'>;
}
declare module 'app/lib/Model.js' {
  declare module.exports: $Exports<'app/lib/Model'>;
}
