// flow-typed signature: b829be588624527e2fb25ef3d2a00cb6
// flow-typed version: <<STUB>>/jest-expo_v^22.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-expo/src/createMockConstants' {
  declare module.exports: any;
}

declare module 'jest-expo/src/expoModules' {
  declare module.exports: any;
}

declare module 'jest-expo/src/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-expo/src/createMockConstants.js' {
  declare module.exports: $Exports<'jest-expo/src/createMockConstants'>;
}
declare module 'jest-expo/src/expoModules.js' {
  declare module.exports: $Exports<'jest-expo/src/expoModules'>;
}
declare module 'jest-expo/src/setup.js' {
  declare module.exports: $Exports<'jest-expo/src/setup'>;
}
